main: de.timesnake.extension.special.main.ExSpecial
version: 1.3.0
name: extension-special
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  movers:
  mover:
  mvs:
  holodisplay:
  holod:
