main: de.timesnake.extension.special.main.ExSpecial
version: ${version}
name: extension-special
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.21

commands:
  movers:
  mover:
  mvs:
  holodisplay:
  holod:
